MortgageApi/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using MortgageApi.Models;
using MortgageApi.Services.CustomerNS;
using MortgageApi.ViewModels.CustomerNS;
using System;
using System.Threading.Tasks;

namespace MortgageApi.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ICustomerService _customerService;

        public CustomerController(ICustomerService customerService)
        {
            _customerService = customerService;
        }

        [ApiExplorerSettings(IgnoreApi = true)]
        [Route("~/about-you", Name = "GetCreate")]
        public IActionResult GetCreate()
        {
            return View("Create");
        }

        [ApiExplorerSettings(IgnoreApi = true)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FirstName,LastName,DOB,Email")] CustomerViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var customer = new Customer()
                {
                    Email = viewModel.Email,
                    FirstName = viewModel.FirstName,
                    LastName = viewModel.LastName,
                    DOB = viewModel.DOB
                };

                Guid id = await _customerService.CreateCustomer(customer);
                return RedirectToAction("GetSearchCriteria","Search", new { id=id });
            }
            return View(viewModel);
        }

        [ApiExplorerSettings(IgnoreApi = true)]
        public async Task<IActionResult> Index()
        {
            return View(await _customerService.GetCustomers());
        }
    }
}

MortgageApi/Controllers/MortgageController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MortgageApi.Data;
using MortgageApi.Services.CustomerNS;
using MortgageApi.Services.MortgageNS;
using MortgageApi.ViewModels.MortgageNS;
using System;
using System.Threading.Tasks;

namespace MortgageApi.Controllers
{
    public class MortgageController : Controller
    {
        private readonly DataContext _context;
        private readonly IMortgageService _mortgageService;
        private readonly ICustomerService _customerSevice;

        public MortgageController(DataContext context, ICustomerService customerSevice, IMortgageService mortgageService)
        {
            _context = context;
            _mortgageService = mortgageService;
            _customerSevice = customerSevice;
        }

        [ApiExplorerSettings(IgnoreApi = true)]
        public async Task<IActionResult> Index()
        {
            var mortgages = await _mortgageService.GetMortgages();
            var viewModel = new MortgagesViewModel(mortgages);
            return View(viewModel);
        }

        [ApiExplorerSettings(IgnoreApi = true)]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mortgage = await _context.Mortgages
                .FirstOrDefaultAsync(m => m.Id == id);
            if (mortgage == null)
            {
                return NotFound();
            }

            return View(mortgage);
        }
    }
}

MortgageApi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mortgage Demo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mortgage Api Demo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            @Html.ActionLink("Start Demo", "Index", "Home",null, new {Class="nav-link text-dark"})
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Customers", "Index", "Customer",null, new {Class="nav-link text-dark"})
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Mortgages", "Index", "Mortgage",null, new {Class="nav-link text-dark"})
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="~/swagger">API</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            Developed by Dale Morgan
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>